application-description: 'Aplicacao de controle financeiro'
application-version: 1.6.0
springdoc:
  use-fqn: true
  swagger-ui:
    show-extensions: true
    show-common-extensions: true
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true